const pacientes = new Array(
    {
        nombre: 'Lucia',
        apellido: 'Alvarez',
        edad: 43,
        diagnostico: 'gripe',
        numeroSS: 'A123456'
    },
    {
        nombre: 'Carlos',
        apellido: 'Andres',
        edad: 56,
        diagnostico: 'diabetes',
        numeroSS: 'K34567000',
    },
    {
        nombre: 'Jose',
        apellido: 'Dominguez',
        edad: 67,
        diagnostico: 'alzheimer',
        numeroSS: 'O934571',
    },
    {
        nombre: 'Elena',
        apellido: 'Prados',
        edad: 18,
        diagnostico: 'intoxicacion',
        numeroSS: 'I823455',
    },
    {
        nombre: 'Maria',
        apellido: 'Carreño',
        edad: 45,
        diagnostico: 'cancer',
        numeroSS: 'P123454',
    },
    {
        nombre: 'Pepe',
        apellido: 'Guzman',
        edad: 89,
        diagnostico: 'depresion',
        numeroSS: 'Q12362548',
    },
    {
        nombre: 'Ricardo',
        apellido: 'Gomez',
        edad: 24,
        diagnostico: 'diabetes',
        numeroSS: 'I324610',
    },
    {
        nombre: 'Maria',
        apellido: 'Gutierrez',
        edad: 28,
        diagnostico: 'gripe',
        numeroSS: 'Q345126',
    },
    {
        nombre: 'Manuel',
        apellido: 'Castillo',
        edad: 27,
        diagnostico: 'coronavirus',
        numeroSS: 'Q124500',
    },
    {
        nombre: 'Pepe',
        apellido: 'Gomez',
        edad: 65,
        diagnostico: 'gripe',
        numeroSS: 'K123652',
    },
    {
        nombre: 'Pepita',
        apellido: 'Juarez',
        edad: 48,
        diagnostico: 'gripe',
        numeroSS: 'S231583',
    },
    {
        nombre: 'Pablo',
        apellido: 'Motos',
        edad: 55,
        diagnostico: 'diabetes',
        numeroSS: 'R23456',
    },
    {
        nombre: 'Pepe',
        apellido: 'Villuela',
        edad: 65,
        diagnostico: 'torcedura',
        numeroSS: 'P45678',
    },
    {
        nombre: 'Rodrigo',
        apellido: 'Caicedo',
        edad: 36,
        diagnostico: 'migraña',
        numeroSS: 'R098753',
    },
    {
        nombre: 'David',
        apellido: 'Perez',
        edad: 40,
        diagnostico: 'diabetes',
        numeroSS: 'D245456',
    },

)